// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package srv

import (
	"context"
	"github.com/aserto-dev/aserto-idp-plugin-okta/pkg/oktaclient"
	"github.com/golang/mock/gomock"
)

// Injectors from wire.go:

func NewOktaPlugin() *OktaPlugin {
	contextContext := context.Background()
	oktaPager := NormalPager()
	oktaPlugin := &OktaPlugin{
		ctx:   contextContext,
		pager: oktaPager,
	}
	return oktaPlugin
}

func NewTestOktaPlugin(ctrl *gomock.Controller, pager OktaPager) *OktaPlugin {
	contextContext := context.Background()
	mockOktaClient := oktaclient.NewMockOktaClient(ctrl)
	oktaPlugin := &OktaPlugin{
		ctx:    contextContext,
		client: mockOktaClient,
		pager:  pager,
	}
	return oktaPlugin
}
